"""Add_user_email_and_wallet

Revision ID: 36d061584c2a
Revises: f45db1acfb6d
Create Date: 2026-04-07 01:10:40.962595

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d061584c2a'
down_revision: Union[str, Sequence[str], None] = 'f45db1acfb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_wallet_address'), 'user', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wallet_address'), table_name='user')
    op.drop_column('user', 'wallet_address')
    # ### end Alembic commands ###
