"""Add_prices_and_active_status_to_catalog

Revision ID: 36d54d997de2
Revises: 7fd8d97ca83c
Create Date: 2026-04-07 03:46:42.065163

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d54d997de2'
down_revision: Union[str, Sequence[str], None] = '7fd8d97ca83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemcatalog', sa.Column('price_axg', sa.Float(), nullable=True))
    op.add_column('itemcatalog', sa.Column('price_gal', sa.Float(), nullable=True))
    op.add_column('itemcatalog', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemcatalog', 'is_active')
    op.drop_column('itemcatalog', 'price_gal')
    op.drop_column('itemcatalog', 'price_axg')
    # ### end Alembic commands ###
