"""Add Axolotito model

Revision ID: 7c389ea808a0
Revises: bcfcc86f06cf
Create Date: 2026-05-22 11:08:46.707324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c389ea808a0'
down_revision: Union[str, Sequence[str], None] = 'bcfcc86f06cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axolotito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skin_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gill_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eye_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mouth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tail_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forehead_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('limb_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('stat_salinity', sa.Float(), nullable=False),
    sa.Column('stat_luck', sa.Float(), nullable=False),
    sa.Column('stat_focus', sa.Float(), nullable=False),
    sa.Column('stat_stamina', sa.Integer(), nullable=False),
    sa.Column('stat_charisma', sa.Float(), nullable=False),
    sa.Column('stat_agility', sa.Float(), nullable=False),
    sa.Column('stat_wisdom', sa.Float(), nullable=False),
    sa.Column('stat_strength', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('energy_current', sa.Integer(), nullable=False),
    sa.Column('blockchain_token_id', sa.Integer(), nullable=True),
    sa.Column('dna_sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_token_id')
    )
    op.create_index(op.f('ix_axolotito_user_id'), 'axolotito', ['user_id'], unique=False)
    op.execute("UPDATE webitoincubation SET is_frozen = FALSE WHERE is_frozen IS NULL")
    op.execute("UPDATE webitoincubation SET frozen_clicks_left = 0 WHERE frozen_clicks_left IS NULL")
    op.alter_column('webitoincubation', 'is_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('webitoincubation', 'frozen_clicks_left',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webitoincubation', 'frozen_clicks_left',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('webitoincubation', 'is_frozen',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_axolotito_user_id'), table_name='axolotito')
    op.drop_table('axolotito')
    # ### end Alembic commands ###
