"""Crear_Catalogo_e_Inventario

Revision ID: 7fd8d97ca83c
Revises: 36d061584c2a
Create Date: 2026-04-07 01:33:04.874876

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd8d97ca83c'
down_revision: Union[str, Sequence[str], None] = '36d061584c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemcatalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_type', sa.Enum('EGG', 'BOOSTER', 'CARD', 'ACCESSORY', 'BOARD', name='itemtype'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarity'), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('item_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemcatalog_name'), 'itemcatalog', ['name'], unique=False)
    op.create_table('playerinventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itemcatalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerinventory_user_id'), 'playerinventory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerinventory_user_id'), table_name='playerinventory')
    op.drop_table('playerinventory')
    op.drop_index(op.f('ix_itemcatalog_name'), table_name='itemcatalog')
    op.drop_table('itemcatalog')
    # ### end Alembic commands ###
