"""add_bot_config_fields

Revision ID: 919663c1bc6e
Revises: 7c389ea808a0
Create Date: 2026-05-22 11:32:39.784588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919663c1bc6e'
down_revision: Union[str, Sequence[str], None] = '7c389ea808a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('axolotito', sa.Column('bot_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('axolotito', sa.Column('bot_budget_axg', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('axolotito', sa.Column('bot_loss_limit_axg', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('axolotito', sa.Column('bot_profit_limit_axg', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('axolotito', sa.Column('assigned_board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'axolotito', 'itemcatalog', ['assigned_board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'axolotito', type_='foreignkey')
    op.drop_column('axolotito', 'assigned_board_id')
    op.drop_column('axolotito', 'bot_profit_limit_axg')
    op.drop_column('axolotito', 'bot_loss_limit_axg')
    op.drop_column('axolotito', 'bot_budget_axg')
    op.drop_column('axolotito', 'bot_enabled')
    # ### end Alembic commands ###
