"""webito incubation

Revision ID: 9eb3204e5c88
Revises: 36d54d997de2
Create Date: 2026-04-07 09:38:12.603243

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb3204e5c88'
down_revision: Union[str, Sequence[str], None] = '36d54d997de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webitoincubation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('clicks_hoy', sa.Integer(), nullable=False),
    sa.Column('clicks_totales', sa.Integer(), nullable=False),
    sa.Column('calor_actual', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_eclosion_estimada', sa.DateTime(), nullable=False),
    sa.Column('ultimo_click', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webitoincubation_user_id'), 'webitoincubation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webitoincubation_user_id'), table_name='webitoincubation')
    op.drop_table('webitoincubation')
    # ### end Alembic commands ###
