"""webito incubation 2

Revision ID: bcfcc86f06cf
Revises: 9eb3204e5c88
Create Date: 2026-04-07 10:00:26.761137

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfcc86f06cf'
down_revision: Union[str, Sequence[str], None] = '9eb3204e5c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webitoincubation', sa.Column('is_frozen', sa.Boolean(), nullable=True))
    op.add_column('webitoincubation', sa.Column('frozen_clicks_left', sa.Integer(), nullable=True))
    op.add_column('webitoincubation', sa.Column('protected_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webitoincubation', 'protected_until')
    op.drop_column('webitoincubation', 'frozen_clicks_left')
    op.drop_column('webitoincubation', 'is_frozen')
    # ### end Alembic commands ###
