"""slot_xp_preservation

Revision ID: de45f7199b37
Revises: e13048ae5137
Create Date: 2026-06-10 01:09:44.992114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de45f7199b37'
down_revision: Union[str, Sequence[str], None] = 'e13048ae5137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chainoutbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chainoutbox_tx_hash'), 'chainoutbox', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_chainoutbox_user_id'), 'chainoutbox', ['user_id'], unique=False)
    op.create_table('playerboardslot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('preserved_xp', sa.Integer(), nullable=False),
    sa.Column('boards_created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_index')
    )
    op.create_index(op.f('ix_playerboardslot_user_id'), 'playerboardslot', ['user_id'], unique=False)
    op.create_table('activegamestate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cards_drawn_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_states_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turns_played', sa.Integer(), nullable=False),
    sa.Column('current_card_id', sa.Integer(), nullable=True),
    sa.Column('tension_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['gameroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activegamestate_room_id'), 'activegamestate', ['room_id'], unique=True)
    op.drop_table('manualmodeevent')
    op.add_column('axolotito', sa.Column('last_staking_claim', sa.DateTime(), nullable=True))
    op.add_column('axolotito', sa.Column('accrued_unclaimed', sa.Integer(), nullable=False))
    op.add_column('axolotito', sa.Column('mentorship_count', sa.Integer(), nullable=False))
    op.add_column('axolotito', sa.Column('tutored_by_id', sa.Integer(), nullable=True))
    op.add_column('playerboard', sa.Column('slot_index', sa.Integer(), nullable=True))
    op.add_column('playerboard', sa.Column('slot_generation', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_playerboard_slot_index'), 'playerboard', ['slot_index'], unique=False)
    op.add_column('user', sa.Column('last_f2p_daily_claim_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('f2p_daily_claim_streak', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('lunar_streak_day', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('lunar_week', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('lunar_last_claim_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('lunar_cycles_completed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

    # Backfill: asignar slot_index a tablas activas (no muertas) en orden de creación
    op.execute("""
        WITH ranked AS (
            SELECT id,
                   ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at) AS rn
            FROM playerboard
            WHERE is_dead = FALSE
        )
        UPDATE playerboard
        SET slot_index = ranked.rn
        FROM ranked
        WHERE playerboard.id = ranked.id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lunar_cycles_completed')
    op.drop_column('user', 'lunar_last_claim_at')
    op.drop_column('user', 'lunar_week')
    op.drop_column('user', 'lunar_streak_day')
    op.drop_column('user', 'f2p_daily_claim_streak')
    op.drop_column('user', 'last_f2p_daily_claim_at')
    op.drop_index(op.f('ix_playerboard_slot_index'), table_name='playerboard')
    op.drop_column('playerboard', 'slot_generation')
    op.drop_column('playerboard', 'slot_index')
    op.drop_column('axolotito', 'tutored_by_id')
    op.drop_column('axolotito', 'mentorship_count')
    op.drop_column('axolotito', 'accrued_unclaimed')
    op.drop_column('axolotito', 'last_staking_claim')
    op.create_table('manualmodeevent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('daily_open_time', sa.TIME(), nullable=True),
    sa.Column('daily_close_time', sa.TIME(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), nullable=False),
    sa.Column('tabla_cost_gal', sa.FLOAT(), nullable=False),
    sa.Column('max_tablas_per_player', sa.INTEGER(), nullable=False),
    sa.Column('prize_pool_pct', sa.FLOAT(), nullable=False),
    sa.Column('platform_fee_pct', sa.FLOAT(), nullable=False),
    sa.Column('jackpot_contribution_pct', sa.FLOAT(), nullable=False),
    sa.Column('bonus_gal_on_win', sa.FLOAT(), nullable=False),
    sa.Column('drop_multiplier', sa.FLOAT(), nullable=False),
    sa.Column('xp_bonus_pct', sa.FLOAT(), nullable=False),
    sa.Column('griton_delay_ms', sa.INTEGER(), nullable=False),
    sa.Column('griton_repeats', sa.BOOLEAN(), nullable=False),
    sa.Column('win_condition', sa.VARCHAR(), nullable=False),
    sa.Column('max_game_duration_s', sa.INTEGER(), nullable=True),
    sa.Column('tie_behavior', sa.VARCHAR(), nullable=False),
    sa.Column('allowed_modes', sa.VARCHAR(), nullable=False),
    sa.Column('max_players_per_room', sa.INTEGER(), nullable=False),
    sa.Column('min_players_to_start', sa.INTEGER(), nullable=False),
    sa.Column('room_wait_timeout_s', sa.INTEGER(), nullable=False),
    sa.Column('vip_only', sa.BOOLEAN(), nullable=False),
    sa.Column('min_axo_level', sa.INTEGER(), nullable=True),
    sa.Column('first_time_only', sa.BOOLEAN(), nullable=False),
    sa.Column('broadcast_message', sa.VARCHAR(), nullable=True),
    sa.Column('broadcast_sent', sa.BOOLEAN(), nullable=False),
    sa.Column('broadcast_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('auto_reminder', sa.BOOLEAN(), nullable=False),
    sa.Column('notify_room_start', sa.BOOLEAN(), nullable=False),
    sa.Column('post_event_summary', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_activegamestate_room_id'), table_name='activegamestate')
    op.drop_table('activegamestate')
    op.drop_index(op.f('ix_playerboardslot_user_id'), table_name='playerboardslot')
    op.drop_table('playerboardslot')
    op.drop_index(op.f('ix_chainoutbox_user_id'), table_name='chainoutbox')
    op.drop_index(op.f('ix_chainoutbox_tx_hash'), table_name='chainoutbox')
    op.drop_table('chainoutbox')
    # ### end Alembic commands ###
