"""Crear_Banco_y_Wallets

Revision ID: f45db1acfb6d
Revises: 6a5ba04702d6
Create Date: 2026-04-06 21:56:08.706693

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45db1acfb6d'
down_revision: Union[str, Sequence[str], None] = '6a5ba04702d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactionledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('AXOGEMA', 'GEMA_ALGA', 'FRAGMENTO_COMUN', 'FRAGMENTO_RARO', 'FRAGMENTO_EPICO', 'FRAGMENTO_LEGENDARIO', name='currencytype'), nullable=False),
    sa.Column('tx_type', sa.Enum('DEPOSIT', 'WITHDRAW', 'P2P_SEND', 'P2P_RECEIVE', 'MARKET_BUY', 'MARKET_SELL', 'REWARD', 'BOOSTER_PURCHASE', 'CRAFTING', name='transactiontype'), nullable=False),
    sa.Column('related_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fee_applied', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionledger_user_id'), 'transactionledger', ['user_id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('axogemas', sa.Float(), nullable=False),
    sa.Column('gemas_alga', sa.Float(), nullable=False),
    sa.Column('frag_comun', sa.Integer(), nullable=False),
    sa.Column('frag_raro', sa.Integer(), nullable=False),
    sa.Column('frag_epico', sa.Integer(), nullable=False),
    sa.Column('frag_legendario', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.privy_did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_index(op.f('ix_transactionledger_user_id'), table_name='transactionledger')
    op.drop_table('transactionledger')
    # ### end Alembic commands ###
